# basic options
title: Alexander's Website
author: Alexander Chen
email: alexanderlchen@gmail.com
description: A wonderful site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: jekyll-theme-slate
